openapi: 3.0.4
info:
  title: Farmacia Tech # Nombre de tu API
  description: "API REST para gestión de ventas en una farmacia"
  version: 1.0.0                     # Versión de tu API
  contact:
    name: ITQ Nexus distributed and cloud systems
    email: l21212050@queretaro.tecnm.mx
  license:
    name: Nexus 1.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html  

servers: 
  - url: http://localhost:8080/api/v1
    description: Ambiente local
  - url: http://192.168.10.1:8080/api/v1
    description: Ambiente para entregar OAS  

tags: 
  - name: pharmacys
    description: "Crud basico para las sucursales de la farmacia"
  - name: sales
    description: "Administracion de las ventas de la farmacia"
  - name: products
    description: "Administracion de los productos de la farmacia"
  - name: employes
    description: "Administracion de los empleados de la farmacia"

paths:
  /pharmacy:
    get:
      tags:
        - pharmacys
      summary: Obtiene todas las sucursales de la farmacia.
      description: "Obtener todas las sucursales de farmacia"
      responses:
        '200':
          description: "todo bien"
    post:
      tags:
        - pharmacys
      summary: Agrega una nueva sucursal de farmacia.
      operationId: postPharmacy
      requestBody:
        description: "solicitud de registro de una nueva sucursal de la farmacia"
        content:
          application/json:
            schema:
              type: object
              required: 
                - pharmacyId
                - pharmacyName
                - direction
              properties:
                pharmacyId:
                  title: "Identificar unido de la sucursal"
                  type: integer
                  example: "1"
                pharmacyName:
                  title: "Nombre de la sucursal"
                  type: string
                  minLength: 5
                  maxLength: 100
                  example: "Farmacia tech 1"
                direction:
                  title: nombre cliente
                  type: string
                  minLength: 5
                  maxLength: 300
                  example: "Real Solare 46, CP: 76246, Queretaro"
      responses:
        '200':
          description: "Solicitud de registro correcta"
  /pharmacy/{pharmacyId}:
    put:
      tags:
        - pharmacys
      summary: Edita la farmacia por Id.
      description: "solicitud de modificacion de una sucursalde la farmacia"
      operationId: putPharmacyById
      parameters:
        - name: pharmacyId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: 
                - pharmacyName
                - direction
              properties:
                pharmacyName:
                  title: "Nombre de la sucursal"
                  type: string
                  minLength: 5
                  maxLength: 100
                  example: "Farmacia tech 1"
                direction:
                  title: nombre cliente
                  type: string
                  minLength: 5
                  maxLength: 300
                  example: "Real Solare 46, CP: 76246, Queretaro"
      responses:
        '200':
          description: "Solicitud de edicion correcta"           
    delete:
      tags:
        - pharmacys
      summary: Eliminar la farmacia por Id.
      description: "solicitud de eliminacion de una sucursalde la farmacia"
      operationId: deletePharmacyById
      parameters:
        - name: pharmacyId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: "Solicitud de eliminacion de ejecuto correctamente"
